task :default do
    puts "build\tbuild executable using ocra"
    puts "test\trun unit tests"
end

task :build do
    puts `ocra main.rb --output main.exe --gemfile Gemfile --gem-minimal`
end

task :example do
    puts `ruby main.rb --refs ./samples/DESADV_D01B_ecosio.edi`
end

task :test do
    paths = ARGV.map { |arg| File.file?(arg) ? arg : nil }.compact
    puts `ruby main.rb --test #{paths.join(" ")}`
end