require 'csv'
require 'json'

require './html.rb'
require './reference.rb'
require './version.rb'
require './punctuation.rb'
require './line.rb'
require './date.rb'

require './segments/una.rb'
require './segments/unh.rb'
require './segments/unb.rb'
require './segments/unt.rb'
require './segments/unz.rb'
require './segments/bgm.rb'
require './segments/dtm.rb'
require './segments/ftx.rb'
require './segments/rff.rb'
require './segments/nad.rb'
require './segments/tax.rb'
require './segments/lin.rb'
require './segments/qty.rb'
require './segments/imd.rb'
require './segments/pia.rb'
require './segments/mea.rb'
require './segments/pri.rb'
require './segments/gin.rb'
require './segments/cps.rb'
require './segments/pci.rb'
require './segments/loc.rb'
require './segments/inv.rb'

require './document.rb'