task :default do
    puts "build\tbuild executable using ocra"
    puts "test\trun unit tests"
end

task :build do
    puts `ocra main.rb --output main.exe --gemfile Gemfile --gem-minimal`
end

task :test do
    puts `ruby main.rb`
end